# text/yaml
name: ci # (1)
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material # (3)
      - run: mkdocs gh-deploy --force
      
# END configuration for GitHub Action

# From: https://github.com/squidfunk/mkdocs-material/blob/master/docs/publishing-your-site.md#github-pages
#
# 1. You can change the name to your liking.
#
# 2. At some point, GitHub renamed `master` to `main`. If your default branch
#    is named `master`, you can safely remove `main`, vice versa.
#
# 3. This is the place to install further [MkDocs plugins] or Markdown
#    extensions with `pip` to be used during the build:
#
#     ``` sh
#     pip install \
#       mkdocs-material \
#       mkdocs-awesome-pages-plugin \
#       ...
#     ```
#
