# text/yaml
name: githubpages-mkdoc-deploy # (1)
# This GitHub action deploys a static copy of tbe 'docs' folder to be hosted by GitHub Pages
# The resulting html files will be in the "gh_pages" branch of this project.
# The "Pages" section of the project settings page on GitHub must be pointed to the root of that branch.

on:
  # Trigger the workflow on push or pull request,
  # but only for the main (or "master") branch 
  push:
    branches:
      - main
      - master
    paths:
      - docs/**
      - mkdocs.yml
      - .github/workflows/githubpages-mkdoc-deploy.yaml
      
  pull_request:
    branches:
      - main
      - master
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/_githubpages/mkdocs-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      # - run: pip install mkdocs-material # (3)
      - name: Install dependencies
        run: pip install -r docs/_githubpages/mkdocs-requirements.txt
      # - run: mkdocs gh-deploy --force
      - name: Build and deploy docs and push to GitHub Pages
        run: |
          mkdocs gh-deploy --config-file docs/_githubpages/mkdocs.yml --remote-branch gh-pages --force --verbose

# END configuration for GitHub Action

# From: https://github.com/squidfunk/mkdocs-material/blob/master/docs/publishing-your-site.md#github-pages
#
# 1. You can change the name to your liking.
#
# 2. At some point, GitHub renamed `master` to `main`. If your default branch
#    is named `master`, you can safely remove `main`, vice versa.
#
# 3. This is the place to install further [MkDocs plugins] or Markdown
#    extensions with `pip` to be used during the build:
#
#     ``` sh
#     pip install \
#       mkdocs-material \
#       mkdocs-awesome-pages-plugin \
#       ...
#     ```
#
